version: '3.6'
services:
  jenkinsmaster:
    build: .
    image: jenkinsmaster:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /tmp/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
